name: Release to PyPI

# on:
#   release:
#     types: [published]
#     branches: [main]
on:
  push:
    branches: [main]
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source"
        uses: actions/checkout@v2

      - name: "Setup python"
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: "Install poetry"
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      # Install package dependencies
      - name: "Install dependencies"
        run: poetry install

      # Configure poetry
      - name: "Configure poetry"
        env:
          pypi_token: ${{ secrets.TEST_PY_PI }}
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config pypi-token.testpypi $pypi_token

      - name: "Build and publish to PyPi"
        run: |
          poetry publish --build -r testpypi
