name: Release to PyPI

on:
  release:
    types: [published]
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Set up a Python environment
      - uses: actions/setup-python@v3
        with:
          python-version: 3.11

      # Install poetry
      - run: |
          python -m pip install --upgrade pip
          pip install poetry

      # Install package dependencies
      - run: poetry install

      # Configure poetry
      - name: "Configure poetry"
        env:
          pypi_token: ${{ secrets.TEST_PY_PI }}
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config pypi-token.testpypi $pypi_token

      # Build and upload the package to PyPI
      - run: |
          poetry publish --build
